# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generated by tasks/scripts/release.py, then edited for `brew bump` automation:
# the `version` stanza is omitted and resources track the parent version.

class Openshell < Formula
  desc "Safe, private runtime for autonomous AI agents"
  homepage "https://github.com/NVIDIA/OpenShell"
  url "https://github.com/NVIDIA/OpenShell/releases/download/v0.0.116/openshell-aarch64-apple-darwin.tar.gz"
  sha256 "e582f2374053bebac8e6aaeb4a369931b7d4bb97bd55055e2c02e85502627e22"
  license "Apache-2.0"

  livecheck do
    url "https://github.com/NVIDIA/OpenShell/releases"
    strategy :github_releases
  end

  depends_on arch: :arm64
  depends_on macos: :big_sur

  resource "openshell-gateway" do
    url "https://github.com/NVIDIA/OpenShell/releases/download/v0.0.116/openshell-gateway-aarch64-apple-darwin.tar.gz"
    sha256 "f192d3d737c125264e13ef73458541df2ca6a9eb2fa599736a7f2587d5d2ce8d"

    livecheck do
      formula :parent
    end
  end

  resource "openshell-driver-vm" do
    url "https://github.com/NVIDIA/OpenShell/releases/download/v0.0.116/openshell-driver-vm-aarch64-apple-darwin.tar.gz"
    sha256 "8024b8443cfee668b74dce3d348e308d3f576e624ef36af3bc20f79451e96cff"

    livecheck do
      formula :parent
    end
  end

  def install
    odie "OpenShell Homebrew formula currently supports macOS only" unless OS.mac?

    bin.install "openshell"

    resource("openshell-gateway").stage do
      bin.install "openshell-gateway"
    end

    resource("openshell-driver-vm").stage do
      libexec.install "openshell-driver-vm"
    end

    (libexec/"openshell-gateway-homebrew-service").write <<~SH
      #!/bin/sh
      set -eu

      if [ -z "${HOME:-}" ]; then
        echo "HOME must be set for Docker TLS bind mounts" >&2
        exit 1
      fi

      xdg_config_home="${XDG_CONFIG_HOME:-${HOME}/.config}"
      xdg_gateway_env="${xdg_config_home}/openshell/gateway.env"
      prefix_gateway_env="#{var}/openshell/gateway.env"
      if [ -f "${xdg_gateway_env}" ]; then
        set -a
        . "${xdg_gateway_env}"
        set +a
      elif [ -f "${prefix_gateway_env}" ]; then
        set -a
        . "${prefix_gateway_env}"
        set +a
      fi

      docker_tls_dir="${HOME}/.local/state/openshell/homebrew/tls"
      mkdir -p "${docker_tls_dir}/server"
      mkdir -p "${docker_tls_dir}/client"
      mkdir -p "${docker_tls_dir}/jwt"
      chmod 700 "${docker_tls_dir}" "${docker_tls_dir}/server" "${docker_tls_dir}/client" "${docker_tls_dir}/jwt"
      /usr/bin/install -m 0644 "#{var}/openshell/tls/ca.crt" "${docker_tls_dir}/ca.crt"
      /usr/bin/install -m 0644 "#{var}/openshell/tls/server/tls.crt" "${docker_tls_dir}/server/tls.crt"
      /usr/bin/install -m 0600 "#{var}/openshell/tls/server/tls.key" "${docker_tls_dir}/server/tls.key"
      /usr/bin/install -m 0644 "#{var}/openshell/tls/client/tls.crt" "${docker_tls_dir}/client/tls.crt"
      /usr/bin/install -m 0600 "#{var}/openshell/tls/client/tls.key" "${docker_tls_dir}/client/tls.key"
      /usr/bin/install -m 0600 "#{var}/openshell/tls/jwt/signing.pem" "${docker_tls_dir}/jwt/signing.pem"
      /usr/bin/install -m 0644 "#{var}/openshell/tls/jwt/public.pem" "${docker_tls_dir}/jwt/public.pem"
      /usr/bin/install -m 0644 "#{var}/openshell/tls/jwt/kid" "${docker_tls_dir}/jwt/kid"
      export OPENSHELL_LOCAL_TLS_DIR="${OPENSHELL_LOCAL_TLS_DIR:-${docker_tls_dir}}"

      xdg_gateway_config="${xdg_config_home}/openshell/gateway.toml"
      prefix_gateway_config="#{var}/openshell/gateway.toml"

      if [ -z "${OPENSHELL_GATEWAY_CONFIG:-}" ] && [ ! -f "${xdg_gateway_config}" ] && [ -f "${prefix_gateway_config}" ]; then
        exec "#{opt_bin}/openshell-gateway" --config "${prefix_gateway_config}"
      fi

      exec "#{opt_bin}/openshell-gateway"
    SH
    chmod 0755, libexec/"openshell-gateway-homebrew-service"
  end

  def post_install
    (var/"openshell/gateway").mkpath
    (var/"openshell/vm-driver").mkpath
    (var/"log/openshell").mkpath

    # Regenerating the CA on upgrade would invalidate the mTLS certificates
    # already registered with `openshell gateway add`, so only generate a
    # missing or incomplete set. The certificates do not expire.
    tls_files = %w[
      ca.crt ca.key
      server/tls.crt server/tls.key
      client/tls.crt client/tls.key
      jwt/signing.pem jwt/public.pem jwt/kid
    ]
    unless tls_files.all? { |tls_file| (var/"openshell/tls"/tls_file).exist? }
      system bin/"openshell-gateway", "generate-certs", "--output-dir", var/"openshell/tls",
             "--server-san", "host.openshell.internal"
    end

    entitlements = var/"openshell/openshell-driver-vm.entitlements.plist"
    entitlements.atomic_write <<~XML
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
          <key>com.apple.security.hypervisor</key>
          <true/>
      </dict>
      </plist>
    XML

    system "/usr/bin/codesign", "--entitlements", entitlements, "--force", "-s", "-", libexec/"openshell-driver-vm"
  end

  service do
    run opt_libexec/"openshell-gateway-homebrew-service"
    keep_alive successful_exit: false
    log_path var/"log/openshell/openshell-gateway.out.log"
    error_log_path var/"log/openshell/openshell-gateway.err.log"
  end

  def caveats
    <<~EOS
      Start or restart the local gateway with:
        brew services restart openshell

      Register it with the OpenShell CLI:
        openshell gateway add https://127.0.0.1:17670 --local --name openshell
    EOS
  end

  test do
    assert_match "openshell ", shell_output("#{bin}/openshell --version")
  end
end
